// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: CaseFlame2.proto

package Data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaseFlame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameId int32    `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Frame   *SubData `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
}

func (x *CaseFlame) Reset() {
	*x = CaseFlame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CaseFlame2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseFlame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseFlame) ProtoMessage() {}

func (x *CaseFlame) ProtoReflect() protoreflect.Message {
	mi := &file_CaseFlame2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseFlame.ProtoReflect.Descriptor instead.
func (*CaseFlame) Descriptor() ([]byte, []int) {
	return file_CaseFlame2_proto_rawDescGZIP(), []int{0}
}

func (x *CaseFlame) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *CaseFlame) GetFrame() *SubData {
	if x != nil {
		return x.Frame
	}
	return nil
}

type SubData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     int32      `protobuf:"varint,1,opt,name=name,proto3" json:"name,omitempty"`
	Total    int32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Self     int32      `protobuf:"varint,3,opt,name=self,proto3" json:"self,omitempty"`
	Calls    int32      `protobuf:"varint,4,opt,name=calls,proto3" json:"calls,omitempty"`
	Gcalloc  int32      `protobuf:"varint,5,opt,name=gcalloc,proto3" json:"gcalloc,omitempty"`
	Timems   int32      `protobuf:"varint,6,opt,name=timems,proto3" json:"timems,omitempty"`
	Selfms   int32      `protobuf:"varint,7,opt,name=selfms,proto3" json:"selfms,omitempty"`
	Children []*SubData `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *SubData) Reset() {
	*x = SubData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CaseFlame2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubData) ProtoMessage() {}

func (x *SubData) ProtoReflect() protoreflect.Message {
	mi := &file_CaseFlame2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubData.ProtoReflect.Descriptor instead.
func (*SubData) Descriptor() ([]byte, []int) {
	return file_CaseFlame2_proto_rawDescGZIP(), []int{1}
}

func (x *SubData) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *SubData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubData) GetSelf() int32 {
	if x != nil {
		return x.Self
	}
	return 0
}

func (x *SubData) GetCalls() int32 {
	if x != nil {
		return x.Calls
	}
	return 0
}

func (x *SubData) GetGcalloc() int32 {
	if x != nil {
		return x.Gcalloc
	}
	return 0
}

func (x *SubData) GetTimems() int32 {
	if x != nil {
		return x.Timems
	}
	return 0
}

func (x *SubData) GetSelfms() int32 {
	if x != nil {
		return x.Selfms
	}
	return 0
}

func (x *SubData) GetChildren() []*SubData {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_CaseFlame2_proto protoreflect.FileDescriptor

var file_CaseFlame2_proto_rawDesc = []byte{
	0x0a, 0x10, 0x43, 0x61, 0x73, 0x65, 0x46, 0x6c, 0x61, 0x6d, 0x65, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x46, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x65, 0x46, 0x6c, 0x61, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x05, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x07, 0x53,
	0x75, 0x62, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x65, 0x6c, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x63,
	0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x63, 0x61,
	0x6c, 0x6c, 0x6f, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x6d, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6c, 0x66, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65,
	0x6c, 0x66, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x43,
	0x61, 0x73, 0x65, 0x46, 0x61, 0x6c, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CaseFlame2_proto_rawDescOnce sync.Once
	file_CaseFlame2_proto_rawDescData = file_CaseFlame2_proto_rawDesc
)

func file_CaseFlame2_proto_rawDescGZIP() []byte {
	file_CaseFlame2_proto_rawDescOnce.Do(func() {
		file_CaseFlame2_proto_rawDescData = protoimpl.X.CompressGZIP(file_CaseFlame2_proto_rawDescData)
	})
	return file_CaseFlame2_proto_rawDescData
}

var file_CaseFlame2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CaseFlame2_proto_goTypes = []interface{}{
	(*CaseFlame)(nil), // 0: CaseFlame
	(*SubData)(nil),   // 1: SubData
}
var file_CaseFlame2_proto_depIdxs = []int32{
	1, // 0: CaseFlame.frame:type_name -> SubData
	1, // 1: SubData.children:type_name -> SubData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CaseFlame2_proto_init() }
func file_CaseFlame2_proto_init() {
	if File_CaseFlame2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CaseFlame2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseFlame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CaseFlame2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CaseFlame2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CaseFlame2_proto_goTypes,
		DependencyIndexes: file_CaseFlame2_proto_depIdxs,
		MessageInfos:      file_CaseFlame2_proto_msgTypes,
	}.Build()
	File_CaseFlame2_proto = out.File
	file_CaseFlame2_proto_rawDesc = nil
	file_CaseFlame2_proto_goTypes = nil
	file_CaseFlame2_proto_depIdxs = nil
}
