// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: protoFile/CaseFunRowAloneForGo.proto

package Data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllCaseFunRowAlone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allvalues []*CaseFunRowAlone `protobuf:"bytes,1,rep,name=allvalues,proto3" json:"allvalues,omitempty"`
}

func (x *AllCaseFunRowAlone) Reset() {
	*x = AllCaseFunRowAlone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllCaseFunRowAlone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllCaseFunRowAlone) ProtoMessage() {}

func (x *AllCaseFunRowAlone) ProtoReflect() protoreflect.Message {
	mi := &file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllCaseFunRowAlone.ProtoReflect.Descriptor instead.
func (*AllCaseFunRowAlone) Descriptor() ([]byte, []int) {
	return file_protoFile_CaseFunRowAloneForGo_proto_rawDescGZIP(), []int{0}
}

func (x *AllCaseFunRowAlone) GetAllvalues() []*CaseFunRowAlone {
	if x != nil {
		return x.Allvalues
	}
	return nil
}

type CaseFunRowAlone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Frames []*CaseFunRowInfoAlone `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
}

func (x *CaseFunRowAlone) Reset() {
	*x = CaseFunRowAlone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseFunRowAlone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseFunRowAlone) ProtoMessage() {}

func (x *CaseFunRowAlone) ProtoReflect() protoreflect.Message {
	mi := &file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseFunRowAlone.ProtoReflect.Descriptor instead.
func (*CaseFunRowAlone) Descriptor() ([]byte, []int) {
	return file_protoFile_CaseFunRowAloneForGo_proto_rawDescGZIP(), []int{1}
}

func (x *CaseFunRowAlone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CaseFunRowAlone) GetFrames() []*CaseFunRowInfoAlone {
	if x != nil {
		return x.Frames
	}
	return nil
}

type CaseFunRowInfoAlone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame   int32 `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
	Calls   int32 `protobuf:"varint,2,opt,name=calls,proto3" json:"calls,omitempty"`     //calls
	Gcalloc int32 `protobuf:"varint,3,opt,name=gcalloc,proto3" json:"gcalloc,omitempty"` //gcalloc
	Timems  int32 `protobuf:"varint,4,opt,name=timems,proto3" json:"timems,omitempty"`   //timems
	Selfms  int32 `protobuf:"varint,5,opt,name=selfms,proto3" json:"selfms,omitempty"`   //selfms
}

func (x *CaseFunRowInfoAlone) Reset() {
	*x = CaseFunRowInfoAlone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseFunRowInfoAlone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseFunRowInfoAlone) ProtoMessage() {}

func (x *CaseFunRowInfoAlone) ProtoReflect() protoreflect.Message {
	mi := &file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseFunRowInfoAlone.ProtoReflect.Descriptor instead.
func (*CaseFunRowInfoAlone) Descriptor() ([]byte, []int) {
	return file_protoFile_CaseFunRowAloneForGo_proto_rawDescGZIP(), []int{2}
}

func (x *CaseFunRowInfoAlone) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *CaseFunRowInfoAlone) GetCalls() int32 {
	if x != nil {
		return x.Calls
	}
	return 0
}

func (x *CaseFunRowInfoAlone) GetGcalloc() int32 {
	if x != nil {
		return x.Gcalloc
	}
	return 0
}

func (x *CaseFunRowInfoAlone) GetTimems() int32 {
	if x != nil {
		return x.Timems
	}
	return 0
}

func (x *CaseFunRowInfoAlone) GetSelfms() int32 {
	if x != nil {
		return x.Selfms
	}
	return 0
}

var File_protoFile_CaseFunRowAloneForGo_proto protoreflect.FileDescriptor

var file_protoFile_CaseFunRowAloneForGo_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x2f, 0x43, 0x61, 0x73, 0x65,
	0x46, 0x75, 0x6e, 0x52, 0x6f, 0x77, 0x41, 0x6c, 0x6f, 0x6e, 0x65, 0x46, 0x6f, 0x72, 0x47, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x73,
	0x65, 0x46, 0x75, 0x6e, 0x52, 0x6f, 0x77, 0x41, 0x6c, 0x6f, 0x6e, 0x65, 0x12, 0x2e, 0x0a, 0x09,
	0x61, 0x6c, 0x6c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x46, 0x75, 0x6e, 0x52, 0x6f, 0x77, 0x41, 0x6c, 0x6f, 0x6e,
	0x65, 0x52, 0x09, 0x61, 0x6c, 0x6c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x53, 0x0a, 0x0f,
	0x43, 0x61, 0x73, 0x65, 0x46, 0x75, 0x6e, 0x52, 0x6f, 0x77, 0x41, 0x6c, 0x6f, 0x6e, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x46, 0x75, 0x6e, 0x52, 0x6f, 0x77,
	0x49, 0x6e, 0x66, 0x6f, 0x41, 0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x73, 0x22, 0x8b, 0x01, 0x0a, 0x13, 0x43, 0x61, 0x73, 0x65, 0x46, 0x75, 0x6e, 0x52, 0x6f, 0x77,
	0x49, 0x6e, 0x66, 0x6f, 0x41, 0x6c, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x63, 0x61, 0x6c, 0x6c, 0x6f, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x63, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x74, 0x69, 0x6d, 0x65, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x66, 0x6d,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x66, 0x6d, 0x73, 0x42,
	0x09, 0x5a, 0x07, 0x2f, 0x47, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protoFile_CaseFunRowAloneForGo_proto_rawDescOnce sync.Once
	file_protoFile_CaseFunRowAloneForGo_proto_rawDescData = file_protoFile_CaseFunRowAloneForGo_proto_rawDesc
)

func file_protoFile_CaseFunRowAloneForGo_proto_rawDescGZIP() []byte {
	file_protoFile_CaseFunRowAloneForGo_proto_rawDescOnce.Do(func() {
		file_protoFile_CaseFunRowAloneForGo_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoFile_CaseFunRowAloneForGo_proto_rawDescData)
	})
	return file_protoFile_CaseFunRowAloneForGo_proto_rawDescData
}

var file_protoFile_CaseFunRowAloneForGo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protoFile_CaseFunRowAloneForGo_proto_goTypes = []interface{}{
	(*AllCaseFunRowAlone)(nil),  // 0: AllCaseFunRowAlone
	(*CaseFunRowAlone)(nil),     // 1: CaseFunRowAlone
	(*CaseFunRowInfoAlone)(nil), // 2: CaseFunRowInfoAlone
}
var file_protoFile_CaseFunRowAloneForGo_proto_depIdxs = []int32{
	1, // 0: AllCaseFunRowAlone.allvalues:type_name -> CaseFunRowAlone
	2, // 1: CaseFunRowAlone.frames:type_name -> CaseFunRowInfoAlone
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protoFile_CaseFunRowAloneForGo_proto_init() }
func file_protoFile_CaseFunRowAloneForGo_proto_init() {
	if File_protoFile_CaseFunRowAloneForGo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllCaseFunRowAlone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseFunRowAlone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoFile_CaseFunRowAloneForGo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseFunRowInfoAlone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoFile_CaseFunRowAloneForGo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoFile_CaseFunRowAloneForGo_proto_goTypes,
		DependencyIndexes: file_protoFile_CaseFunRowAloneForGo_proto_depIdxs,
		MessageInfos:      file_protoFile_CaseFunRowAloneForGo_proto_msgTypes,
	}.Build()
	File_protoFile_CaseFunRowAloneForGo_proto = out.File
	file_protoFile_CaseFunRowAloneForGo_proto_rawDesc = nil
	file_protoFile_CaseFunRowAloneForGo_proto_goTypes = nil
	file_protoFile_CaseFunRowAloneForGo_proto_depIdxs = nil
}
